version: '3.1'
services:
  gateway_edge:
    image: mhm-edge-gateway-edge
    networks:
      - mhm_network
    ports:
      - 8090:8088
      - 8094:8043
    volumes:
      - mhm-edge-gateway-edge:/usr/local/bin/ignition/data
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_USERNAME=mhm
      - GATEWAY_ADMIN_PASSWORD_FILE=/run/secrets/gateway-admin-password
      - IGNITION_EDITION=edge
      - TZ=Pacific/Auckland 
    secrets:
      - gateway-admin-password
    command: "-n mhm-edge-gateway-edge"
secrets:
  gateway-admin-password:
    file: /opt/ignition-edge/secrets/GATEWAY_ADMIN_PASSWORD
volumes:
  mhm-edge-gateway-edge:

networks:
  mhm_network:
    external: true