version: '3'

services:
  stresser:
    image: progrium/stress
    command: ["--cpu", "2"]
    restart: always

  telegraf:
    image: telegraf
    volumes:
      - /opt/testing/telegraf:/etc/telegraf

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /opt/testing/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - /opt/testing/grafana:/var/lib/grafana
