version: '3.1'
services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/ansible/portainer_data:/data
